version: '3'
services:
    cofrinhoapp:
        build: .
        cgroup_parent: marcus
        volumes:
            - ./:/var/www
        depends_on:
            - cofrinhoapp-postgres
            - cofrinhoapp-redis
        ports:
            - 9000:9000

    cofrinhoapp-postgres:
        image: postgres:12-alpine
        cgroup_parent: marcus
        restart: always
        ports:
            - 5432:5432
        volumes:
            - "./.docker/postgres/data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=cofrinho_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    cofrinhoapp-redis:
        image: redis:alpine
        cgroup_parent: marcus
        volumes:
            - ./.docker/redis:/data
        ports:
            - 6379:6379

    cofrinhoapp-nginx:
        build: ./.docker/nginx
        cgroup_parent: marcus
        restart: always
        ports:
            - 80:80
        volumes:
            - ./:/var/www
            - ./.docker/log/nginx:/var/log/nginx
        depends_on:
            - cofrinhoapp
